---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-reader-linking
  namespace: test-ns
subjects:
  - kind: User
    name: ravi
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
... 
